spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/topic?useTimezone=true&serverTimezone=UTC'
    username: 'root'
    password: 'Projeto@123'
    driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 8081
